### PR TITLE
Destructive changes

### PR DESCRIPTION
**Pull request by ralphcallaway**
super hacky #3

### CODE REVIEW

**Comment by ralphcallaway** [comment]
code is pretty ugly and needs a lot more testing, but figured i'd get your input

**Comment by ChuckJonas** [comment]
Seems like a solid first pass.  Not sure why, but I hadn't considered just creating a separate project to generate the package.xml (sure, its a little hackish, but no worse than the rest of this).

Two thoughts:

1. We probably need to fix #13 before shipping this, otherwise you could possibly delete things that shouldn't be deleted
1. Maybe there should be a flag to turn this on/off?  Would be helpful in CI processes where you want to best possible chance of deploy success.  In that case you would almost just want a separate deployment for just the destructive changes that you could run as a secondary deployment.

**Comment by ralphcallaway** [comment]
1. so i think the same hack could be used for #13, build a package.xml for the current project and do an intersection with the destructiveChanges.xml, anything in the intersection we pull back out of the destructiveChanges.xml. if a static resource is totally deleted it won't be in the current project package.xml anymore, if it was modified it'll still be there.

2. disagree and commit

**Comment by ChuckJonas** [comment]
1. Technically the static resource / aura / lwc should also be included in the package since it's been modified (via a partial deletion).  It might make more sense to just check this case when parsing the changes from git diff.  

Given that the "hack" solution is going to require creating another tmp folder, copying all source from a ref, executing a sfdx command, parsing two xml files, subtracting the difference and writing back out, it _might_ actually be less work anyways.

**Comment by ralphcallaway** [comment]
definitely needs testing, and plenty of room to improve code organization still, but looks like ready to start trying

tested as follows
- created apex class
- deleted apex class 
- deleted .svg from lightning component

confirmed 
- new apex class is deploy assets
- remaining lightning components in deploy assets 
- deleted apex class in destructiveChanges.xml
- if `--nodelete` flag passed we don't generated destructiveChanges.xml

let me know if you have more feedback

**Comment by ChuckJonas** [comment]
Running some Tests: (some of these bugs could be in the current version)

Deleting a class: ✅ 

Deleting a single file from "directory" metadata type: ✅ 

Deleting an entire "directory" metadata type ❌ 

- `D force-app/main/default/aura/abac`

Error: 
```
{ [Error: ENOENT: no such file or directory, scandir 'force-app/main/default/aura/abac']
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'force-app/main/default/aura/abac' }
```

Deletion only ❌ 

Just do a single deletion.

ERR: `WARNING: No changes found!`

Delete Custom Field ❌ 

- Delete a single field from a custom object

> ERROR running force:source:convert:  Cannot read property 'attributes' of null

**Pull request merged**
