### PR TITLE
Test methods

### PR DESCRIPTION
**Pull request by ralphcallaway**
just asserting package.xml exists, going to expand to cover full output, but wanted to get something up for feedback

i know that an integration test isn't the fastest, but i think while you're dialing in the internal structure this sort of test would be helpful

nb: doesn't help code coverage since i'm spawning to run the command, i spent a bit of time trying to use the oclif helpers, but was getting bogged down just trying to get the test to run at all

### CODE REVIEW

**Comment by ralphcallaway** [comment]
ps - not ready to merge, want to expand the test quite a bit and cover some different scenarios

**Comment by ChuckJonas** [comment]
Seems like a decent start.   Oddly the very first time I executed `npm test`  it failed, but has passed on following runs. 

org_test_ts__Working_Tree__—_sfdx-git-packager

Not sure what's going on... can't consistently reproduce.

Managing these test asset projects inside of the source seems a bit tricky, but the approach you've chosen [seems like the best](https://stackoverflow.com/questions/44776451/how-can-i-safely-commit-a-git-directory).  Looks like you can use `--git-dir` & `--work-tree` to still issue commands without having to rename `.notgit`.

Ex: `git --git-dir=test/projects/base/.notgit --work-tree=test/projects/base/ status`

My one suggestion would be that we only have one test project and instead use branches for each test case. This should help keep our source size down as the number of test cases grows.  

For these integration tests, we can just pass the test case branch via `--sourceref`.

**Comment by ralphcallaway** [comment]
@ChuckJonas sweet find, was looking all over for how to deal with repos and repos. good news, there are corresponding GIT_DIR and GIT_WORK_TREE environmental variables, so we can turn things back on when making the exec call.

and good idea about using a bunch of branches for various test scenarios, although i'd expect a repo with a fair amount of state isn't much a space saver relative to several repos with less state

**Comment by ralphcallaway** [comment]
@ChuckJonas take a peek and let me know what you think, feeling ready to go and start expanding test cases
- one test project
- folder with expected outputs
- test runner that runs with supplied branch refs and compares to expected output dir

only have one case now, but adding more should be pretty quick, just need to setup the compare branches in the test project, add the expected output, and add it a call to the test suite

let me know which test cases would be the most useful to you was thinking
- update a class
- delete a class 
- partial delete a folder resource
- fully delete a folder resource

**Comment by ChuckJonas** [comment]
[This answer](https://stackoverflow.com/a/8198276/800619) explains how git stores files. Seems like there is some conflicting info.  Either way, I think it will just be a bit tidier and easy to manage a test single repo.

Hadn't thought much about assertions... It would be easy enough to check the package.xml using something like [xml2js](https://www.npmjs.com/package/xml2js), however, asserting that the source is also as expected is probably the more important part anyways.

I think the approach makes sense.  Maybe we just have an `expected` directory in the test project with a package that reflects the branch name. We could use the tool itself to generate the expected packages the first time (manually checked of course).

I think the test cases above would be a good start.   ➕ on the test runner.  Ideally the only thing that changes from test to test is the branch (the expected output could be resolved from the branch name).  Once it's setup we could hammer through test cases.  Recursively checking two folders for equivalency shouldn't be TOO bad (might be a library we can leverage for this).  Changes to how `sfdx force:source:convert` formats the `package.xml` could break tests in the future I can't imagine it would happen too often.

**Example:**

Test Case: Modifying a class
Branch: `class-modification`
Expected Result: `tests/project/expected/class-modification`

**Some Other test potential test cases:**

- Creating a class
- Renaming a class
- Adding a new field
- Removing a field
- Modifying a field
- Changing object properties
- Deleting an object
- Updating a mirrored `-meta.xml` file
- Modifying a single file static resource

**Comment by ChuckJonas** [comment]
just saw you've already made commits.  3 steps ahead of me.  Nice work

**Comment by ralphcallaway** [comment]
added a bunch of tests, and organized things so it's easy to add more, see the readme for details (it's not quite there, the test runner still has to be updated with new cases, haven't figured out how to do an 'it' statement inside a loop properly)

assuming the integration test will get slow, so split it off from another test suite

up to 5 integration tests, a couple more and we should be able to really hack the main code with confidence

**Comment by ChuckJonas** [comment]
So... Trying to fix the static resource issue.  Seems like a bug with the `dir-compare` and binary files.

I hate to say it but the way the commits are sequential makes this very hard to modify/update any individual the integration tests.

I think it would make more sense if we just started with a project with a master branch that has pretty much everything we need to modify/delete/add and we branch off of master every time.

That way the test are aways on the diff between the master branch and whatever changes you made only in the test branch.

**Comment by ralphcallaway** [comment]
@ChuckJonas i follow you, but if you need a new test, why not just append? with a bunch of different branches off one node, it's still going to be challenging to modify the base project set

and if you did want to adjust a test, you could always just append and change the setup as needed

the challenge i had is i didn't know everything i wanted to test, so it wasn't obvious what was in the base project, and doing it this way was pretty fast ...

thanks for the pointer on the dir-compare, it's got a bunch of options hopefully i can figure it out or just loosen things up a bit on the assertions

also, see https://www.atlassian.com/git/tutorials/rewriting-history and scroll to the "Changing older or multiple commits" if you want to check out how to use rebase to hack at those older commits

**Comment by ralphcallaway** [comment]
ps - let me know if the current repo is a deal breaker, i'll disagree and commit

**Comment by ChuckJonas** [comment]
I went ahead and recreated it.  I think this will be much more manageable but let me know if you disagree.  

project__Git_

The downside to this approach is when we need to update the master branch (to test modify/delete on a new metadata type), we'll have to merge master back into each of the test branches. We could write a script to help with this.

All tests are now passing (had to use lwc to `single file deleted from folder test case`).



I'm going to push my changes, so we'll have to start a new PR.  From now on, it probably makes the most sense for you to just work directly off this repo instead of your fork (so we can both work off the same origin:branch).

The only other concern I have is with the `genIntegrationTestOutput.ts`, but everytime you run it, you are at risk of putting the test cases out of a "correct state".  

Example: 

Say I add a new feature, then add a new test case. I then execute `npm run gen` to update all the test outputs.

If my new feature actually broke something, then all the tests cases would be updated to reflect this broken output.

... However, (thinking as I type this) I guess you would see these changes in source control so as long as you don't blind `git add -a` you should notice something is off.

**Comment by ralphcallaway** [comment]
agreed on the gen integration risks, not quite sure what we would do about it

in theory you would only want to run it when adding new tests cases, and you'd want to make sure the output was correct

... and thinking more, maybe we just updated it to only run if the directory doesn't exist? if you want to "reset" you just wipe out the output folder for the test before running ...

**Pull request merged**
